# NUMPY

In [3]:
import numpy as np

In [9]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [10]:
%timeit [x ** 2 for x in big_list]

9.62 ms ± 1.36 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit big_array ** 2

74.8 μs ± 1.63 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
a = np.array([1,2,4,5,])
print(a)

[1 2 4 5]


In [16]:
b = np.array([[1,2,3,4],[4,8,9,5]])
print(b)

[[1 2 3 4]
 [4 8 9 5]]


In [18]:
a = np.array([0,0,0,0,])
print(a)

[0 0 0 0]


In [19]:
zero = np.zeros((2,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [22]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [23]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [30]:
print(rng.integers(1,10,size = (3,3)))

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [31]:
print(rng.normal(loc=0 ,scale = 1, size=5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


In [32]:
## Array Attributes

M = np.array([[1,2,3],[4,5,8]])
M

array([[1, 2, 3],
       [4, 5, 8]])

In [33]:
print(M.ndim)

2


In [34]:
print(M.size)

6


In [35]:
print(M.dtype)

int64


In [37]:
print(M.shape)

(2, 3)


In [40]:
ints = np.array([1,2,3],dtype=np.int32)

In [41]:
ints.dtype

dtype('int32')

In [43]:
floats = np.array([1,2,3],dtype = np.float64)
floats.dtype

dtype('float64')

In [44]:
# indexing and slicing

x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
print(x[5])

15


In [48]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
print(M[1,2])

7


In [50]:
M[0]
M[1]

array([5, 6, 7, 8])

In [51]:
print(M[:,1])

[ 2  6 10]


In [52]:
## Vector Operation

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a + b)

[11 22 33 44]


In [53]:
print(a * b)

[ 10  40  90 160]


In [54]:
## Broadcasting

a = np.array ([1,2,3])
b = 10

In [55]:
print(a + b)

[11 12 13]


In [61]:
a = np.array ([[1,2,3],[4,8,9]])
b = np.array ([10,20,30])

print(a + b)

[[11 22 33]
 [14 28 39]]


In [62]:
a = np.array([[1,5],
            [5,8]])
a.shape

(2, 2)

In [64]:
b = np.array ([10,20,30])
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 